### ISSUE TITLE
Create example sending a request with Yew and GraphQL

### ISSUE THREAD

**Issue by mnnxp** [mnnxp/yew-graphql-app#1]
Hello,
I have need sending request to GraphQL server from client with Yew, but I not found real world example (any one example).
If that bad idea - please tell me, why is it?
Any help with this would be really helpful.

Regards,
Ivan

**Comment by sansx** [comment]
Hey, check this out [yew-graphql-demo](https://github.com/sansx/yew-graphql-demo), but I use graphql_client to request Graphql. if you are confused feel free to ask me. ;)

**Comment by mnnxp** [comment]
Wow, it worked! Thank you! :)
